### ISSUE TITLE
SyntaxError Line80

### ISSUE THREAD

**Issue by BORNIOS** [emiliobog/Evil-Sofia#2]
Tengo un problema, al ejecutarlo me marca error de Sintaxis en la linea 80

> python sofia.py
  File "C:\Users\borni\Desktop\Evil-Sofia-master\sofia.py", line 80
    print time.strftime("                    %I:%M:%S")
          ^
SyntaxError: invalid syntax

![Sofia](https://user-images.githubusercontent.com/65147899/98175292-f00c7d00-1ebb-11eb-9aa3-358755eaeb2c.jpg)

Nota: Uso Python 3.9 (Instalado desde MStore)

**Comment by emiliobog** [comment]
Hola, Evil-Sofia usa **PYTHON 2.7** para funcionar instala python 2.7 y reintenta, Saludos 

_#BOG_
